---
- name: Deploy Portfolio Website
  hosts: port
  become: true

  tasks:
    - name: Update packages 
      shell: yes | yum update 

    - name: Install Apache web server
      yum:
        name: httpd
        state: present

    # - name: Ensure the "/var/www/html/" directory exist
    #   file:
    #     path: /var/www/html/
    #     state: directory

    - name: Copy website files to server
      copy:
        src: ./
        dest: /var/www/html/
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
