---
- name: Update packages for Rhel
  yum:
    name: "*"
    state: latest

- name: Install Httpd web server
  yum:
    name: httpd
    state: present

- name: Ensure the "/var/www/html/" directory exists
  file:
    path: /var/www/html/
    state: directory

- name: Copy website files to server
  copy:
    src: "../files/"  
    dest: /var/www/html/
  notify:
    - Restart Httpd

